### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bigfarts** [jpmac26/gba-mus-ripper#15]
Would you be able to add a license to this repo? I would like to use this code as a reference for implementing a similar ripper but to module format rather than MIDI and I want to make sure I can attribute and use this code under terms that are fair to you.

Thank you!

**Comment by CaptainSwag101** [comment]
Certainly, and thank you for being so upfront with your request! The README file from Bregalad (the original developer) simply says that you're free to use it and improve upon it as long as you provide attribution, though since I am a staunch advocate for source code disclosure, I plan to license things under the GNU GPLv3 license. I hope that is satisfactory?

**Comment by bigfarts** [comment]
Yes, no problem! Thank you!
