### ISSUE TITLE
psg_data.raw file is present but the soundfont ripper is unable to find

### ISSUE THREAD

**Issue by Tau5** [jpmac26/gba-mus-ripper#7]

**Comment by CaptainSwag101** [comment]
The programs in this repo have always had issues with file paths, check and make sure there are no spaces in your file path otherwise you may get strange issues. I've tried fixing this several times but I just can't seem to make it work properly. Also, this repo is not really being maintained anymore, mainly due to the fact that I have a hard time working with this code. Sorry for the inconvenience.
